import Head from "next/head";
import Image from "next/image";
import rightArrow from "../public/arrow-right-line.svg";
import Footer from "../components/footer";
import DescrPopup from "../components/DescrPopup";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen container mx-auto">
                <div className="grid grid-rows-6 bg-blue-400 border-black">
                    <div className="flex flex-col w-1/3 bg-slate-600 col-start-1 border-black">
                        <h1 className="font-mono text-7xl ">
                            DIGITAL <br />
                            ART <br />
                            STUDIO <br />
                        </h1>
                        <div className="flex flex-col w-2/3">
                            <h3 className="text-xl w-full font-mono font-bold">
                                Check my artworks
                            </h3>
                            <Image
                                src={rightArrow}
                                alt="arrow-icon"
                                className="h-20 w-2/3"
                            />
                        </div>
                        <Footer />
                    </div>

                    <div className="flex justify-end align-center  w-2/3 bg-green-300 col-start-2 col-end-4">
                        <div className="flex flex-wrap w-full  justify-center items-center content-center">
                            <DescrPopup
                                title="PEOPLE"
                                text="AI technologies allow me to draw a portraits in any
                        style you like. If you don't know what style you want to
                        choose, I will choose the best one for you. You can
                        print out the resulting portrait or use it as an avatar
                        on social networks."
                            />
                            <DescrPopup
                                title="CONCEPTS"
                                text="Neural networks help me to generate
                            incredible landscapes, shapes, images,
                            views. If you value art in your interior or
                            you need images to illustrate something,
                            this option will definitely suit you."
                            />
                            <DescrPopup
                                title="REDRAW"
                                text="The capabilities of artificial intelligence
                            allow me to correct individual parts of
                            images or redraw the entire image. I can
                            copy both the image style and the very
                            concept of the location of objects. The
                            degree of similarity can also be adjusted,
                            so make sure you don't have any copyright
                            issues before ordering."
                            />
                            <DescrPopup
                                title="CUSTOM"
                                text="Everything else is in this category. 
                            I will be glad to receive a variety of unusual orders.
                            I assure you, neural networks allow you to create 
                            any graphical objects."
                            />
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
